config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  resources :resumes, only: [:index, :new, :create, :destroy]

  resources :education_backgrounds
  resources :sibling_backgrounds
  resources :family_backgrounds
  resources :personal_backgrounds
  get 'sessions/new'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  root 'sessions#new'
end

app/models/sibling_background.rb
class SiblingBackground < ApplicationRecord
end

app/controllers/sibling_backgrounds_controller.rb
class SiblingBackgroundsController < ApplicationController
  before_action :set_sibling_background, only: [:show, :edit, :update, :destroy]

  # GET /sibling_backgrounds
  # GET /sibling_backgrounds.json
  def index
    @sibling_backgrounds = SiblingBackground.all
  end

  # GET /sibling_backgrounds/1
  # GET /sibling_backgrounds/1.json
  def show
  end

  # GET /sibling_backgrounds/new
  def new
    @sibling_background = SiblingBackground.new
  end

  # GET /sibling_backgrounds/1/edit
  def edit
  end

  # POST /sibling_backgrounds
  # POST /sibling_backgrounds.json
  def create
    params[:sibling_background][:user_id] = current_user.id

    @sibling_background = SiblingBackground.new(sibling_background_params)

    respond_to do |format|
      if @sibling_background.save
        format.html { redirect_to @sibling_background, notice: 'Sibling background was successfully created.' }
        format.json { render :show, status: :created, location: @sibling_background }
      else
        format.html { render :new }
        format.json { render json: @sibling_background.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sibling_backgrounds/1
  # PATCH/PUT /sibling_backgrounds/1.json
  def update
    respond_to do |format|
      if @sibling_background.update(sibling_background_params)
        format.html { redirect_to @sibling_background, notice: 'Sibling background was successfully updated.' }
        format.json { render :show, status: :ok, location: @sibling_background }
      else
        format.html { render :edit }
        format.json { render json: @sibling_background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sibling_backgrounds/1
  # DELETE /sibling_backgrounds/1.json
  def destroy
    @sibling_background.destroy
    respond_to do |format|
      format.html { redirect_to sibling_backgrounds_url, notice: 'Sibling background was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sibling_background
      @sibling_background = SiblingBackground.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sibling_background_params
      params.require(:sibling_background).permit(:user_id, :sibling_name, :sibling_age, :sibling_marital_status, :sibling_residence)
    end
end

app/helpers/sibling_backgrounds_helper.rb
module SiblingBackgroundsHelper
end

app/views/sibling_backgrounds/_form.html.erb
<%= form_for(sibling_background) do |f| %>
  <% if sibling_background.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sibling_background.errors.count, "error") %> prohibited this sibling_background from being saved:</h2>

      <ul>
      <% sibling_background.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div> -->

  <div class="field">
    <%= f.label :sibling_name %>
    <%= f.text_field :sibling_name %>
  </div>

  <div class="field">
    <%= f.label :sibling_age %>
    <%= f.number_field :sibling_age %>
  </div>

  <div class="field">
    <%= f.label :sibling_marital_status %>
    <%= f.text_field :sibling_marital_status %>
  </div>

  <div class="field">
    <%= f.label :sibling_residence %>
    <%= f.text_field :sibling_residence %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sibling_backgrounds/edit.html.erb
<h1>Editing Sibling Background</h1>

<%= render 'form', sibling_background: @sibling_background %>

<%= link_to 'Show', @sibling_background %> |
<%= link_to 'Back', sibling_backgrounds_path %>

app/views/sibling_backgrounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sibling Backgrounds</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Sibling name</th>
      <th>Sibling age</th>
      <th>Sibling marital status</th>
      <th>Sibling residence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sibling_backgrounds.each do |sibling_background| %>
      <tr>
        <td><%= sibling_background.user_id %></td>
        <td><%= sibling_background.sibling_name %></td>
        <td><%= sibling_background.sibling_age %></td>
        <td><%= sibling_background.sibling_marital_status %></td>
        <td><%= sibling_background.sibling_residence %></td>
        <td><%= link_to 'Show', sibling_background %></td>
        <td><%= link_to 'Edit', edit_sibling_background_path(sibling_background) %></td>
        <td><%= link_to 'Destroy', sibling_background, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sibling Background', new_sibling_background_path %>

app/views/sibling_backgrounds/new.html.erb
<h1>New Sibling Background</h1>

<%= render 'form', sibling_background: @sibling_background %>

<%= link_to 'Back', sibling_backgrounds_path %>

app/views/sibling_backgrounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @sibling_background.user_id %>
</p>

<p>
  <strong>Sibling name:</strong>
  <%= @sibling_background.sibling_name %>
</p>

<p>
  <strong>Sibling age:</strong>
  <%= @sibling_background.sibling_age %>
</p>

<p>
  <strong>Sibling marital status:</strong>
  <%= @sibling_background.sibling_marital_status %>
</p>

<p>
  <strong>Sibling residence:</strong>
  <%= @sibling_background.sibling_residence %>
</p>

<%= link_to 'Edit', edit_sibling_background_path(@sibling_background) %> |
<%= link_to 'Back', sibling_backgrounds_path %>