config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  resources :resumes, only: [:index, :new, :create, :destroy]

  resources :education_backgrounds
  resources :sibling_backgrounds
  resources :family_backgrounds
  resources :personal_backgrounds
  get 'sessions/new'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  root 'sessions#new'
end

app/models/education_background.rb
class EducationBackground < ApplicationRecord
end

app/controllers/education_backgrounds_controller.rb
class EducationBackgroundsController < ApplicationController
  before_action :set_education_background, only: [:show, :edit, :update, :destroy]

  # GET /education_backgrounds
  # GET /education_backgrounds.json
  def index
    @education_backgrounds = EducationBackground.all
  end

  # GET /education_backgrounds/1
  # GET /education_backgrounds/1.json
  def show
  end

  # GET /education_backgrounds/new
  def new
    @education_background = EducationBackground.new
  end

  # GET /education_backgrounds/1/edit
  def edit
  end

  # POST /education_backgrounds
  # POST /education_backgrounds.json
  def create
    params[:education_background][:user_id] = current_user.id
    @education_background = EducationBackground.new(education_background_params)

    respond_to do |format|
      if @education_background.save
        format.html { redirect_to @education_background, notice: 'Education background was successfully created.' }
        format.json { render :show, status: :created, location: @education_background }
      else
        format.html { render :new }
        format.json { render json: @education_background.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /education_backgrounds/1
  # PATCH/PUT /education_backgrounds/1.json
  def update
    respond_to do |format|
      if @education_background.update(education_background_params)
        format.html { redirect_to @education_background, notice: 'Education background was successfully updated.' }
        format.json { render :show, status: :ok, location: @education_background }
      else
        format.html { render :edit }
        format.json { render json: @education_background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /education_backgrounds/1
  # DELETE /education_backgrounds/1.json
  def destroy
    @education_background.destroy
    respond_to do |format|
      format.html { redirect_to education_backgrounds_url, notice: 'Education background was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education_background
      @education_background = EducationBackground.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_background_params
      params.require(:education_background).permit(:user_id, :highest_education_level, :university_of_highest_education_level)
    end
end

app/helpers/education_backgrounds_helper.rb
module EducationBackgroundsHelper
end

app/views/education_backgrounds/_form.html.erb
<%= form_for(education_background) do |f| %>
  <% if education_background.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(education_background.errors.count, "error") %> prohibited this education_background from being saved:</h2>

      <ul>
      <% education_background.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div> -->

  <div class="field">
    <%= f.label :highest_education_level %>
    <%= f.text_field :highest_education_level %>
  </div>

  <div class="field">
    <%= f.label :university_of_highest_education_level %>
    <%= f.text_field :university_of_highest_education_level %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/education_backgrounds/edit.html.erb
<h1>Editing Education Background</h1>

<%= render 'form', education_background: @education_background %>

<%= link_to 'Show', @education_background %> |
<%= link_to 'Back', education_backgrounds_path %>

app/views/education_backgrounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Education Backgrounds</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Highest education level</th>
      <th>University of highest education level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @education_backgrounds.each do |education_background| %>
      <tr>
        <td><%= education_background.user_id %></td>
        <td><%= education_background.highest_education_level %></td>
        <td><%= education_background.university_of_highest_education_level %></td>
        <td><%= link_to 'Show', education_background %></td>
        <td><%= link_to 'Edit', edit_education_background_path(education_background) %></td>
        <td><%= link_to 'Destroy', education_background, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education Background', new_education_background_path %>

app/views/education_backgrounds/new.html.erb
<h1>New Education Background</h1>

<%= render 'form', education_background: @education_background %>

<%= link_to 'Back', education_backgrounds_path %>

app/views/education_backgrounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @education_background.user_id %>
</p>

<p>
  <strong>Highest education level:</strong>
  <%= @education_background.highest_education_level %>
</p>

<p>
  <strong>University of highest education level:</strong>
  <%= @education_background.university_of_highest_education_level %>
</p>

<%= link_to 'Edit', edit_education_background_path(@education_background) %> |
<%= link_to 'Back', education_backgrounds_path %>