config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  resources :resumes, only: [:index, :new, :create, :destroy]

  resources :education_backgrounds
  resources :sibling_backgrounds
  resources :family_backgrounds
  resources :personal_backgrounds
  get 'sessions/new'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  root 'sessions#new'
end

app/models/family_background.rb
class FamilyBackground < ApplicationRecord
end

app/controllers/family_backgrounds_controller.rb
class FamilyBackgroundsController < ApplicationController
  before_action :set_family_background, only: [:show, :edit, :update, :destroy]

  # GET /family_backgrounds
  # GET /family_backgrounds.json
  def index
    @family_backgrounds = FamilyBackground.all
  end

  # GET /family_backgrounds/1
  # GET /family_backgrounds/1.json
  def show
  end

  # GET /family_backgrounds/new
  def new
    @family_background = FamilyBackground.new
  end

  # GET /family_backgrounds/1/edit
  def edit
  end

  # POST /family_backgrounds
  # POST /family_backgrounds.json
  def create
    params[:family_background][:user_id] = current_user.id
    @family_background = FamilyBackground.new(family_background_params)

    respond_to do |format|
      if @family_background.save
        format.html { redirect_to @family_background, notice: 'Family background was successfully created.' }
        format.json { render :show, status: :created, location: @family_background }
      else
        format.html { render :new }
        format.json { render json: @family_background.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /family_backgrounds/1
  # PATCH/PUT /family_backgrounds/1.json
  def update
    respond_to do |format|
      if @family_background.update(family_background_params)
        format.html { redirect_to @family_background, notice: 'Family background was successfully updated.' }
        format.json { render :show, status: :ok, location: @family_background }
      else
        format.html { render :edit }
        format.json { render json: @family_background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /family_backgrounds/1
  # DELETE /family_backgrounds/1.json
  def destroy
    @family_background.destroy
    respond_to do |format|
      format.html { redirect_to family_backgrounds_url, notice: 'Family background was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family_background
      @family_background = FamilyBackground.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_background_params
      params.require(:family_background).permit(:user_id, :my_current_occupaion, :father_current_occupation, :mother_current_occupation, :number_of_siblings)
    end
end

app/helpers/family_backgrounds_helper.rb
module FamilyBackgroundsHelper
end

app/views/family_backgrounds/_form.html.erb
<%= form_for(family_background) do |f| %>
  <% if family_background.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(family_background.errors.count, "error") %> prohibited this family_background from being saved:</h2>

      <ul>
      <% family_background.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div> -->

  <div class="field">
    <%= f.label :my_current_occupaion %>
    <%= f.text_field :my_current_occupaion %>
  </div>

  <div class="field">
    <%= f.label :father_current_occupation %>
    <%= f.text_field :father_current_occupation %>
  </div>

  <div class="field">
    <%= f.label :mother_current_occupation %>
    <%= f.text_field :mother_current_occupation %>
  </div>

  <div class="field">
    <%= f.label :number_of_siblings %>
    <%= f.number_field :number_of_siblings %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/family_backgrounds/edit.html.erb
<h1>Editing Family Background</h1>

<%= render 'form', family_background: @family_background %>

<%= link_to 'Show', @family_background %> |
<%= link_to 'Back', family_backgrounds_path %>

app/views/family_backgrounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Family Backgrounds</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>My current occupaion</th>
      <th>Father current occupation</th>
      <th>Mother current occupation</th>
      <th>Number of siblings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @family_backgrounds.each do |family_background| %>
      <tr>
        <td><%= family_background.user_id %></td>
        <td><%= family_background.my_current_occupaion %></td>
        <td><%= family_background.father_current_occupation %></td>
        <td><%= family_background.mother_current_occupation %></td>
        <td><%= family_background.number_of_siblings %></td>
        <td><%= link_to 'Show', family_background %></td>
        <td><%= link_to 'Edit', edit_family_background_path(family_background) %></td>
        <td><%= link_to 'Destroy', family_background, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Family Background', new_family_background_path %>

app/views/family_backgrounds/new.html.erb
<h1>New Family Background</h1>

<%= render 'form', family_background: @family_background %>

<%= link_to 'Back', family_backgrounds_path %>

app/views/family_backgrounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @family_background.user_id %>
</p>

<p>
  <strong>My current occupaion:</strong>
  <%= @family_background.my_current_occupaion %>
</p>

<p>
  <strong>Father current occupation:</strong>
  <%= @family_background.father_current_occupation %>
</p>

<p>
  <strong>Mother current occupation:</strong>
  <%= @family_background.mother_current_occupation %>
</p>

<p>
  <strong>Number of siblings:</strong>
  <%= @family_background.number_of_siblings %>
</p>

<%= link_to 'Edit', edit_family_background_path(@family_background) %> |
<%= link_to 'Back', family_backgrounds_path %>